connect  'jdbc:derby:demo;create=true';
create schema derbyuser;
CREATE TABLE DERBYUSER.VISIT (VISITID SMALLINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,FIRSTNAME VARCHAR(64) NOT NULL, VISITED TIMESTAMP NOT NULL,PRIMARY KEY(VISITID));
