{{ if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /    # This line is only needed when deploying on IBM Cloud Private.
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress  # The ingress name must be unique for each ingress rule created.
  labels:
    app:  liberty-starter
    component: web-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    tier: frontend

spec:
  rules:
  - host:
    http:
      paths:
      - path: /{{ .Release.Name }}-ui  # This is the url path used to access the service externally.
        backend:
          serviceName: {{ .Release.Name }}-{{ .Chart.Name }} # This is the name of the service to be exposed.
          servicePort: {{ .Values.service.internalPort }}
{{- end }}
