apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: liberty-starter
    component: web-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    tier: frontend

spec:
  type: {{ .Values.service.type }}
  ports:
     - port: {{ .Values.service.internalPort }}
  selector:
    app: liberty-starter
    component: web-app
    tier: frontend
